In [26]:
library(repr)
library(tidyverse)
library(tidymodels)


grades <-read_csv("StudentsPerformance.csv")

colnames(grades) <- make.names(colnames(grades))

grades_selected <- grades %>%
    select (gender, math.score, reading.score, writing.score)

grades_new <- grades_selected %>%
    mutate (average.score = (math.score + reading.score + writing.score) /3) %>%
    mutate (average.score = as_factor (average.score))

grades_new

Parsed with column specification:
cols(
  gender = col_character(),
  `race/ethnicity` = col_character(),
  `parental level of education` = col_character(),
  lunch = col_character(),
  `test preparation course` = col_character(),
  `math score` = col_double(),
  `reading score` = col_double(),
  `writing score` = col_double()
)

     gender math.score reading.score writing.score average.score
1    female 72         72            74            72.6666666666667
2    female 69         90            88            82.3333333333333
3    female 90         95            93            92.6666666666667
4    male   47         57            44            49.3333333333333
5    male   76         78            75            76.3333333333333
6    female 71         83            78            77.3333333333333
7    female 88         95            92            91.6666666666667
8    male   40         43            39            40.6666666666667
9    male   64         64            67            65
10   female 38         60            50            49.3333333333333
11   male   58         54            52            54.6666666666667
12   male   40         52            43            45
13   female 65         81            73            73
14   male   78         72            70            73.3333333333333
15   female 50         53            58            53.6666666666667
16   female 69         75            78            74
17   male   88         89            86            87.6666666666667
18   female 18         32            28            26
19   male   46         42            46            44.6666666666667
20   female 54         58            61            57.6666666666667
21   male   66         69            63            66
22   female 65         75            70            70
23   male   44         54            53            50.3333333333333
24   female 69         73            73            71.6666666666667
25   male   74         71            80            75
26   male   73         74            72            73
27   male   69         54            55            59.3333333333333
28   female 67         69            75            70.3333333333333
29   male   70         70            65            68.3333333333333
30   female 62         70            75            69
⋮    ⋮      ⋮          ⋮             ⋮             ⋮
971  female 89         100           100           96.3333333333333
972  male   78          72            69           73
973  female 53          50            60           54.3333333333333
974  female 49          65            61           58.3333333333333
975  female 54          63            67           61.3333333333333
976  female 64          82            77           74.3333333333333
977  male   60          62            60           60.6666666666667
978  male   62          65            58           61.6666666666667
979  male   55          41            48           48
980  female 91          95            94           93.3333333333333
981  female  8          24            23           18.3333333333333
982  male   81          78            78           79
983  male   79          85            86           83.3333333333333
984  female 78          87            91           85.3333333333333
985  female 74          75            82           77
986  male   57          51            54           54
987  female 40          59            51           50
988  male   81          75            76           77.3333333333333
989  female 44          45            45           44.6666666666667
990  female 67          86            83           78.6666666666667
991  male   86          81            75           80.6666666666667
992  female 65          82            78           75
993  female 55          76            76           69
994  female 62          72            74           69.3333333333333
995  male   63          63            62           62.6666666666667
996  female 88          99            95           94
997  male   62          55            55           57.3333333333333
998  female 59          71            65           65
999  female 68          78            77           74.3333333333333
1000 female 77          86            86           83